$script = <<SCRIPT
  mkdir -p keys/web keys/worker

  ssh-keygen -t rsa -f ./keys/web/tsa_host_key -N ''
  ssh-keygen -t rsa -f ./keys/web/session_signing_key -N ''

  ssh-keygen -t rsa -f ./keys/worker/worker_key -N ''

  cp ./keys/worker/worker_key.pub ./keys/web/authorized_worker_keys
  cp ./keys/web/tsa_host_key.pub ./keys/worker

  export CONCOURSE_EXTERNAL_URL=http://172.16.1.10:8080

  sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose > /dev/null 2>&1
  sudo chmod u+x /usr/local/bin/docker-compose
  sudo docker-compose up -d

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "dellemc/docker"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "file", source: "docker-compose.yml", destination: "$HOME/docker-compose.yml"
  config.vm.provision "shell", inline: $script
end
